### ISSUE TITLE
Unable to get 0.52 of SR15 on yelp*

### ISSUE THREAD

**Issue by Snnzhao** [dengyang17/unicorn#6]
We run your code on yelp*, but can only get about 0.46 of SR15 on yelp*. 
Can you help us with more details on the experiment on yelp*?

**Comment by dengyang17** [comment]
How many episodes did you run for yelp*? If you follow the instructions correctly, you should have reached 0.52 within about 30 episodes on yelp*.

**Comment by Snnzhao** [comment]
We find this problem can be solved with the different feature score( weighted entropy).
Thanks

**Comment by Psiphonc** [comment]
> We find this problem can be solved with the different feature score( weighted entropy). Thanks

I also get 0.46 SR in Yelp* and have checked the feature_score method was set to weight_entropy by default. Could u please kindly offer more detail of solving this problem?
