### ISSUE TITLE
A error in env_enumerated_question.py

### ISSUE THREAD

**Issue by Snnzhao** [dengyang17/unicorn#7]
in updata_reachable_feature():  "self.reachable_feature = list(set(next_reachable_feature) - set(self.user_acc_feature)) " should be " self.reachable_feature = list(set(next_reachable_feature) - set(self.user_acc_feature)- set(self.user_rej_feature))"?

**Comment by dengyang17** [comment]
This is not an error. It is different between binary question setting and enumerate question setting. In enumerate question setting, we have features and small features, where only small features will be deleted during the update, i.e., "self.reachable_small_feature = list(set(next_reachable_small_feature) - filter_small_feature - self.invalid_small_feature)". You may check line 333-335.

**Comment by Snnzhao** [comment]
I get it. Thanks for your answer.
