### ISSUE TITLE
transE_data文件夹里面的文件上传有误

### ISSUE THREAD

**Issue by ghost** [dengyang17/unicorn#8]
请问作者relation2id.txt文件是否上传有错误，貌似上传的是E-Com的关系
<img width="1160" alt="截屏2022-08-13 22 25 32" src="https://user-images.githubusercontent.com/83052201/184498565-77e6ab3c-3da7-4eb8-93bf-d81e4dab5d91.png">

**Comment by ghost** [comment]
请问是我理解的问题，还是进行了关系的聚合？

**Comment by dengyang17** [comment]
In our experiments, we only use these two relations for all datasets. However, there are other types of relations in LastFM and Yelp. If you want to include them, you may generate the transE files with these relations and re-train the transE embeddings. Thanks.

**Comment by ghost** [comment]
好的，我明白了。谢谢您的耐心解答，谢谢
