### ISSUE TITLE
Question about data

### ISSUE THREAD

**Issue by houghtonweihu** [dengyang17/unicorn#9]
I was reading the file entity2id.txt in transE_data/lastfm. The name item_0 appeared two times in the file: "item_0 1801" and "item_0 9233". Could you help me to know the reason for this?

   Thanks!

**Comment by dengyang17** [comment]
Sorry about the mistake. The second item_0 is supposed to be feature_0 and so do other item_* after 9233 id. However, this will not affect the pretraining. 

Thanks.

**Comment by houghtonweihu** [comment]
Thanks @dengyang17 for this help!
